balena-io-modules/abstract-sql-to-typescript

src/index.ts, test/index.ts
=> Fix types for ConceptType fields

src/index.ts, test/index.ts
=> Fix defaulting mode to `read`

src/index.ts, test/index.ts
=> Use the referenced field's data type for foreign keys/concept types

src/index.ts, test/index.ts
=> Add type helpers for dealing with expanded/deferred read types

src/index.ts, test/index.ts
=> Fix PickExpanded/PickDeferred type helpers

src/index.ts, test/index.ts, tsconfig.json
=> Add support for reverse references using relationships info

.husky/pre-commit
Change-type: patch
Signed-off-by: Josh Bowling <josh@monarci.com>
=> Dev: Update pre-commit hook

package.json, test/index.ts
Change-type: patch
Signed-off-by: Carol Schulze <carol@balena.io>
=> Update `abstract-sql-compiler` and `odata-to-abstract-sql`

package.json, src/index.ts
=> Update typings to the minimal subset of the abstract sql model we need

package.json, src/index.ts, test/index.ts
=> Adds webresource typing generation

package.json, src/index.ts
Update @balena/lint from 6.2.2 to 7.0.0
Depends-on: https://github.com/balena-io-modules/node-balena-lint/pull/85
Change-type: patch
=> Update @balena/lint to 7.0.0

src/index.ts
=> Add support for Big Serial

src/index.ts, test/index.ts
=> Improve foreign key typings by referencing the appropriate interface

src/generate.ts, test/index.ts
=> Include reference aliases in generated types

package.json, src/generate.ts, test/index.ts
=> Add support for synonyms that only affect part of the relationship

package.json
=> Make sbvr-types a peer dependency, allow for multiple versions

package.json, src/generate.ts
=> Update @balena/lint to 9.x

package.json
=> Fix built file paths now that package.json is imported rather than required

package.json
=> Fix types export

package.json
=> Fix peerDependency version format

src/generate.ts
=> Add support for writable tables with definitions
